# Generated by Django 5.2.14 on 2026-07-04 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='field',
            field=models.CharField(blank=True, choices=[('general', 'نهم'), ('experimental', 'تجربی'), ('mathematical', 'ریاضی'), ('humanities', 'انسانی')], max_length=20, null=True, verbose_name='رشته'),
        ),
    ]
