# Generated by Django 5.2.14 on 2026-06-24 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('planer', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plans',
            name='relation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.userrelationship'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planer.plans'),
        ),
        migrations.AddField(
            model_name='tasks',
            name='lesson',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='planer.lesson'),
        ),
        migrations.AddField(
            model_name='tasks',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planer.plans'),
        ),
        migrations.AddField(
            model_name='topic',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planer.lesson'),
        ),
        migrations.AddField(
            model_name='tasks',
            name='topic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='planer.topic'),
        ),
        migrations.AddField(
            model_name='video',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planer.topic'),
        ),
    ]
