# Generated by Django 5.2.14 on 2026-07-04 20:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planer', '0002_initial'),
        ('users', '0002_alter_user_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='lesson',
            field=models.CharField(max_length=200),
        ),
        migrations.RemoveField(
            model_name='tasks',
            name='lesson',
        ),
        migrations.RemoveField(
            model_name='plans',
            name='relation',
        ),
        migrations.RemoveField(
            model_name='video',
            name='topic',
        ),
        migrations.AddField(
            model_name='topic',
            name='adress',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='title',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateField()),
                ('days', models.IntegerField()),
                ('relation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.userrelationship')),
                ('topics', models.ManyToManyField(to='planer.topic')),
            ],
        ),
        migrations.AlterField(
            model_name='tasks',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planer.plan'),
        ),
        migrations.DeleteModel(
            name='Lesson',
        ),
        migrations.DeleteModel(
            name='Video',
        ),
        migrations.DeleteModel(
            name='Plans',
        ),
    ]
