# Generated by Django 5.2.14 on 2026-07-04 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planer', '0003_alter_topic_lesson_remove_tasks_lesson_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='adress',
            field=models.CharField(default='', max_length=200),
        ),
    ]
