# Generated by Django 5.2.14 on 2026-07-04 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planer', '0004_alter_topic_adress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='adress',
        ),
        migrations.AlterField(
            model_name='topic',
            name='lesson',
            field=models.CharField(blank=True, choices=[('general', 'زیست'), ('experimental', 'فیزیک'), ('mathematical', 'ریاضی'), ('humanities', 'شیمی')], max_length=20, null=True, verbose_name='درس'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='title',
            field=models.CharField(default='', max_length=200, verbose_name='نام مبحث'),
        ),
    ]
