# Generated by Django 5.2.14 on 2026-07-04 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planer', '0005_remove_topic_adress_alter_topic_lesson_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='field',
            field=models.CharField(blank=True, choices=[('general', 'نهم'), ('experimental', 'تجربی'), ('mathematical', 'ریاضی'), ('humanities', 'انسانی')], max_length=20, null=True, verbose_name='رشته'),
        ),
    ]
